import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  idCount: 4,
  tasks: [
    { id: 4, title: 'Task D', completed: false },
    { id: 3, title: 'Task C', completed: false },
    { id: 2, title: 'Task B', completed: false },
    { id: 1, title: 'Task A', completed: false },
  ],
};

export const taskSlice = createSlice({
  name: 'task',
  initialState,
  reducers: {
    //タスクの新規作成
    newTask: (state, action) => {
      state.idCount++;
      const newItem = {
        id: state.idCount,
        title: action.payload,
        completed: false,
      };
      state.tasks = [newItem, ...state.tasks];
    },
    //タスクのチェックの反転
    completeTask: (state, action) => {
      const task = state.tasks.find((t) => t.id === action.payload.id);
      if (task) {
        task.completed = !task.completed;
      }
    },
    // タスクの削除
    deleteTask: (state, action) => {
      state.tasks = state.tasks.filter((t) => t.id !== action.payload.id);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { newTask, completeTask, deleteTask } = taskSlice.actions;

export const selectTasks = (state) => state.task.tasks;

export default taskSlice.reducer;
